export const FETCH_STATEMENT_REQUEST = 'FETCH_STATEMENT_REQUEST'
export const FETCH_STATEMENT_SUCCESS = 'FETCH_STATEMENT_SUCCESS'
export const FETCH_STATEMENT_FAILURE = 'FETCH_STATEMENT_FAILURE'
export const SET_SORT = 'SET_SORT'